### ISSUE TITLE
Wrapper Function Comments aren't ZShell Friendly

### ISSUE THREAD

**Issue by dkolb** [jantman/vault-aws-creds#4]
```
eval `./vault-aws-creds.py -w`
zsh: parse error near `\n'
```

**Comment by jantman** [comment]
@dkolb Definitely a valid bug, but I don't and have never used zsh, so I'm not really sure what the appropriate fix is. Running ``./vault-aws-creds.py -w`` on its own will yield the wrapper... I'm open to suggestions or help getting it to work with zsh, and/or figuring out how to provide the right wrapper for the shell.

**Comment by dkolb** [comment]
Actually, I think this is a bug that only happens when you try to eval the output for some reason.  I have literally no idea what's going on but I'll close this as the instructions are pretty clear on adding it to your shell's resource file.  :-/  So weird.
