### ISSUE TITLE
Choose TTL

### ISSUE THREAD

**Issue by sudermanjr** [jantman/vault-aws-creds#5]
First of all, awesome work on this.  I really appreciate what's here and how well it works.  

I was wondering if you had thought about adding the ability to set a ttl for the credentials that you request.  I know that vault supports this with sts and iam by adding something like `ttl=120m` after your request, or sending that as a json payload.  

I have been looking through the request script, and while I am taking a bit to parse through all of it, I believe this should be possible.  I I have time I will work on a PR, but in the meantime I figured I would bring it up to you.

**Comment by jantman** [comment]
Andrew,

I hadn't thought about it, but I do think it should be possible. Though its usefulness is limited with STS, as STS temporary credentials are currently limited to a maximum TTL of 60 minutes.

PRs are welcome, or else I can do the work but I probably won't be able to find the time until next week.

**Comment by sudermanjr** [comment]
Actually, that's not true of STS when using an IAM user to create the token (as is the case with Vault)

https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html
`Credentials that are created by IAM users are valid for the duration that you specify, from 900 seconds (15 minutes) up to a maximum of 129600 seconds (36 hours), with a default of 43200 seconds (12 hours); `

I have tested this with a manual request to vault, and I can indeed request a longer token than 1 hr.  If you get to it next week, you will probably beat me to it, but I will keep an eye on this nonetheless. 

Thanks,
Andrew

**Comment by jantman** [comment]
Oops, yeah, sorry, I guess I was thinking about AssumeRole.

Most of the time we use vault short-term creds everyone just uses whatever we set the default TTL to in the policy, but I'll look into how I'd implement this...

**Comment by jantman** [comment]
@sudermanjr ok, I have an implementation of this in the "ttl" branch. However, I'm still running 0.7.3 and from what I can tell this doesn't work with that version or with my policies. My server is configured to allow GET (read), not POST, though the current API docs on vaultproject.org list POST for this endpoint.

Do you think that you could test that the "ttl" branch works correctly?

**Comment by sudermanjr** [comment]
Sorry, I just saw this.  I will try to test that out today or tomorrow.

**Comment by jantman** [comment]
Cool, thanks.

**Comment by sudermanjr** [comment]
Just tested out that branch, and it appears that the TTL still gets set to 1h no matter what I do.  I am going to look into it a little further, but I wanted to let you know.

**Comment by jantman** [comment]
Ok, thanks.

Any chance you could give me an example of the manual request to Vault that gets a token with a longer TTL, especially the URL and parameters?

**Comment by sudermanjr** [comment]
Using the vault client, I can do `vault write <backend name>/sts/<role> ttl=120m` 

Or I can pass a json file `vault write <backend>/sts/<role> @ttl.json` where ttl.json looks something like: 
`
{
      "ttl": "15m"
}
`

**Comment by sudermanjr** [comment]
Just tried it using a curl request to the API, and it worked using this:
`curl --header "X-Vault-Token: VAULT_TOKEN" --request POST --data @ttl.json https://vault.domain:8200/v1/<backend name>/sts/<role>`

This was using the same ttl.json file

**Comment by sudermanjr** [comment]
I figured it out.  You were right that it needs to be a POST request.  On line 468 you specify a GET request no matter what the request type is.  For the STS credentials it needs to be a POST (which always seemed strange to me)

**Comment by jantman** [comment]
@sudermanjr thanks so much for all that. I think I've figured out the source of my confusion...

Apparently Vault has, since 0.6.2, supported both read (GET) and update (POST) on the STS credentials path via [this commit](https://github.com/hashicorp/vault/commit/39b75c6ae93c5f731c05225aafcd33a27287bc79). My company wrote our original policies back in early 2017, apparently before the documentation refactor of March 2017 (sometime just before the release of 0.7.1). As of that time, the documentation listed only the GET method for aws/sts. During the documentation refactor, the docs were updated to change the listed method [from GET](https://github.com/hashicorp/vault/commit/501cf5d0659d7606c16a3c5d089de865710f74cf#diff-e31382f183d5405d2cad64a08ef212f7L631) [to POST](https://github.com/hashicorp/vault/commit/501cf5d0659d7606c16a3c5d089de865710f74cf#diff-b024833598594dfb9835f14783359cebR312) but the code never changed, and they're both still supported.

I used the script below to test the behavior of both GET and POST against 0.7.3 and 0.9.3 using both the default TTL and a specified TTL. From what I can tell, GET always returns the default 3600s TTL even if the documented ``ttl`` parameter is specified; POST respects the TTL parameter.

```bash
#!/bin/bash -x

VAULT_TOKEN='508bb70f-6f8a-20a5-c425-a8a8d415b1d0'
echo "==== VAULT VERSION: 0.9.3"
docker run -e "VAULT_DEV_ROOT_TOKEN_ID=$VAULT_TOKEN" -d --name=vault --cap-add=IPC_LOCK vault:0.9.3
sleep 10
docker exec -e "VAULT_TOKEN=$VAULT_TOKEN" -e "VAULT_ADDR=http://127.0.0.1:8200" vault /bin/vault secrets enable aws
docker exec -e "VAULT_TOKEN=$VAULT_TOKEN" -e "VAULT_ADDR=http://127.0.0.1:8200" vault /bin/vault write aws/config/root access_key=$AWS_ACCESS_KEY_ID secret_key=$AWS_SECRET_ACCESS_KEY region=us-east-1
docker exec -e "VAULT_TOKEN=$VAULT_TOKEN" -e "VAULT_ADDR=http://127.0.0.1:8200" vault /bin/vault write aws/roles/test_sts policy='{"Version": "2012-10-17", "Statement": {"Effect": "Allow", "Action": "ec2:*", "Resource": "*"}}'
docker exec -e "VAULT_TOKEN=$VAULT_TOKEN" -e "VAULT_ADDR=http://127.0.0.1:8200" vault /bin/vault write -force aws/sts/test_sts
docker exec -e "VAULT_TOKEN=$VAULT_TOKEN" -e "VAULT_ADDR=http://127.0.0.1:8200" vault /bin/vault write aws/sts/test_sts ttl=15m
docker exec -e "VAULT_TOKEN=$VAULT_TOKEN" -e "VAULT_ADDR=http://127.0.0.1:8200" vault /bin/vault write aws/sts/test_sts ttl=4h
# Note the vault CLI client can't read with arbitrary params, so we use wget
docker exec vault /usr/bin/wget -O - --header "X-Vault-Token: ${VAULT_TOKEN}" 'http://127.0.0.1:8200/v1/aws/sts/test_sts'
docker exec vault /usr/bin/wget -O - --header "X-Vault-Token: ${VAULT_TOKEN}" 'http://127.0.0.1:8200/v1/aws/sts/test_sts?ttl=15m'
docker exec vault /usr/bin/wget -O - --header "X-Vault-Token: ${VAULT_TOKEN}" 'http://127.0.0.1:8200/v1/aws/sts/test_sts?ttl=4h'

docker stop vault
docker rm vault

echo "==== VAULT VERSION: 0.7.3"
docker run -e "VAULT_DEV_ROOT_TOKEN_ID=$VAULT_TOKEN" -d --name=vault --cap-add=IPC_LOCK vault:0.7.3
sleep 10
docker exec -e "VAULT_TOKEN=$VAULT_TOKEN" -e "VAULT_ADDR=http://127.0.0.1:8200" vault /bin/vault mount aws
docker exec -e "VAULT_TOKEN=$VAULT_TOKEN" -e "VAULT_ADDR=http://127.0.0.1:8200" vault /bin/vault write aws/config/root access_key=$AWS_ACCESS_KEY_ID secret_key=$AWS_SECRET_ACCESS_KEY region=us-east-1
docker exec -e "VAULT_TOKEN=$VAULT_TOKEN" -e "VAULT_ADDR=http://127.0.0.1:8200" vault /bin/vault write aws/roles/test_sts policy='{"Version": "2012-10-17", "Statement": {"Effect": "Allow", "Action": "ec2:*", "Resource": "*"}}'
docker exec -e "VAULT_TOKEN=$VAULT_TOKEN" -e "VAULT_ADDR=http://127.0.0.1:8200" vault /bin/vault write -f aws/sts/test_sts
docker exec -e "VAULT_TOKEN=$VAULT_TOKEN" -e "VAULT_ADDR=http://127.0.0.1:8200" vault /bin/vault write aws/sts/test_sts ttl=15m
docker exec -e "VAULT_TOKEN=$VAULT_TOKEN" -e "VAULT_ADDR=http://127.0.0.1:8200" vault /bin/vault write aws/sts/test_sts ttl=4h
# Note the vault CLI client can't read with arbitrary params, so we use wget
docker exec vault /usr/bin/wget -O - --header "X-Vault-Token: ${VAULT_TOKEN}" 'http://127.0.0.1:8200/v1/aws/sts/test_sts'
docker exec vault /usr/bin/wget -O - --header "X-Vault-Token: ${VAULT_TOKEN}" 'http://127.0.0.1:8200/v1/aws/sts/test_sts?ttl=15m'
docker exec vault /usr/bin/wget -O - --header "X-Vault-Token: ${VAULT_TOKEN}" 'http://127.0.0.1:8200/v1/aws/sts/test_sts?ttl=4h'

docker stop vault
docker rm vault
```

**Comment by jantman** [comment]
fixed in #6

**Comment by jantman** [comment]
#6 is merged to master. thanks so much!

**Comment by sudermanjr** [comment]
Great finds in the docs.  Glad it's working now.  Thanks!
